### PR TITLE
fix #26: declare map*() and install exports as functions not types

### LINKED ISSUE #26: map*() and install() functions should be declared as functions not types
After updating to version 0.40.0 I ran into following error:
``Cannot import the type `mapState` as a value. Use `import type` instead.``.

According to examples in the official documentation, you should declare exported functions in this way:
`declare export function(arg1: arg1Type, ..., argN: argNType): resultType`.

Also, declare actual exported function as a type looks strange:
`import { mapState } from vuex;`
`import type { mapState } from 'vuex';`
`const alias: mapState = mapState; `

### PR DESCRIPTION
**Pull request by purumpum**

### CODE REVIEW

**Comment by btkramm** [comment]
Thanks for this pull-request! Applied those changes locally and now I have a different error when using mapActions.

*Cannot call `mapActions` with array literal bound to `namespace` because array literal is incompatible with string*

```js
...mapActions([
  'addPieceToClipping',
  'removePieceFromClipping',
  'movePieceBetweenClippingCampaigns',
]),
```

I started recently using Flow (yesterday haha) and I'm not sure why it's throwing that error. I guess Flow guest the array of string I'm giving is the `namespace` parameter.

**Comment by sobolevn** [comment]
I have already migrated to TS 😆

**Comment by sobolevn** [comment]
@purumpum do you have any idea how to solve @btkramm's problem?

**Comment by purumpum** [comment]
@btkramm, nice to see that my work is in demand 😄.  I have same issue during the PR preparation and have plans to update the libdef to handle this and other cases base on TypeScript version.

To fix your error we need to declare `mapAction` function twice for cases with and without `namespace` param:
```diff
- declare export function mapActions (namespace?: string, map: Array<string> | Object): Object
+ declare export function mapActions (map: Array<string> | { [key: string]: any }): Object
+ declare export function mapActions (namespace: string, map: Array<string> | { [key: string]: any }): 
```
Note: I also change `map` param declaration because otherwise Flow cannot decide how to handle an array: as array of string or as a general object, so with original declaration we would need to declare type explicitly:

```javascript
mapActions(([
  'addPieceToClipping',
  'removePieceFromClipping',
  'movePieceBetweenClippingCampaigns',
]: Array<string>));
```

Hope it help you.

I will update the PR in a couple of days with fix of this error.

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
@btkramm @purumpum can you please verify that the master version now works for you?
If so. I would be happy to release a new version.

**Comment by purumpum** [comment]
@sobolevn I tested current master against my projects. Everything is fine 😃

**Pull request merged**
